@echo off
echo [FastUIA] Killing old Java processes...
taskkill /F /IM java.exe >nul 2>&1
echo [FastUIA] Cleaning and Rebuilding...
call mvn -f examples/Demo/pom.xml clean compile
echo [FastUIA] Starting Focus Logger (Event-Driven)...
call mvn -f examples/Demo/pom.xml exec:java "-Dexec.mainClass=fastuia.FocusLogger"
